### ISSUE TITLE
Console & BFF deployment

### ISSUE THREAD

**Issue by salman-codewar** [ukama/ukama#619]
**Tasks**

- [x] Console app dockerfile is not able to run build app on deployment need a fix
- [x] BFF app contain 2 servers, once is Gateway which expose all services and the other one is metrics which expose all the subscription services. We need to deploy both these services in same container but on different ports as a separate processes.
- [x] Fix Graphql queries mutation crash server on datasource error
- [x] Console app loading states hooked
